default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: to-Doing_development

test:
  <<: *default
  database: to-doing_test

production:
  <<: *default
  database: to-doing_production
  username: to-doing
  password: <%= ENV['TO-DOING_DATABASE_PASSWORD'] %>
