# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68c33f78cd886070a72808c18a2c997ab52b5cba1d11f01189f03c7ea3babdde170d6fcc696d0d36e5e8f00f1fac1f614dcceb5cfb5ac18338efb80037460dcb

test:
  secret_key_base: 22eac53c3b9db5609d2728600bf91e08d68326dc15bd8da81e389ab3af652c07698f8153738b4c2e0200fe14703d1d07ed820f46f825ec06bb686bd56f5ee020

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
